'use client';
import {AudioLines,Headphones,Clock3,Play,Pause,RotateCcw,Repeat2,Volume2,VolumeX} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
export type Track={id:string;title:string;duration:number;size:number;created:number;expires:number;mime:string};
export function Brand(){return <a className="brand" href="/" aria-label="Afterhours home"><span className="brand-mark"><AudioLines size={23}/></span>afterhours<span className="brand-period">.</span></a>;}
export function Header({right}:{right?:React.ReactNode}){return <header className="header"><Brand/><div className="header-right">{right||<span className="muted header-note"><Headphones size={16}/> A space for listening</span>}</div></header>;}
export const time=(n:number)=>!Number.isFinite(n)?'0:00':`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export function remaining(expires:number,now:number){const m=Math.max(0,Math.ceil((expires-now)/60000));return m>=60?`${Math.floor(m/60)}h ${m%60}m left`:`${m}m left`;}
export function Artwork({active=false}:{active?:boolean}){return <div className={`artwork ${active?'moving':''}`} aria-hidden="true"><div className="sound-mark">{[14,22,35,48,31,57,78,62,96,72,48,85,112,90,65,42,74,98,63,43,55,35,26,38,20,12].map((h,i)=><i key={i} style={{height:h,animationDelay:`${i*.12}s`}}/>)}</div><span className="art-label">AFTERHOURS — AUDIO PREVIEW</span></div>;}
export function Player({track,onExpired}:{track:Track;onExpired?:()=>void}){
 const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[duration,setDuration]=useState(track.duration),[buffer,setBuffer]=useState(0),[loop,setLoop]=useState(false),[volume,setVolume]=useState(1),[waiting,setWaiting]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>{const n=Date.now();setNow(n);if(n>=track.expires){const a=audio.current;if(a){a.pause();a.removeAttribute('src');a.load();}onExpired?.();}},1000);return()=>clearInterval(timer);},[track.expires,onExpired]);
 async function toggle(){const a=audio.current;if(!a)return;if(playing){a.pause();return;}try{setError('');await a.play();}catch{setError('Playback could not start. Try again or check your connection.');setWaiting(false);}}
 const expired=now>=track.expires;
 return <div className="player"><Artwork active={playing&&!waiting}/><div className="player-body"><div className="eyebrow">JUST PRESS PLAY</div><h2>{track.title}</h2><p className="track-sub">Press play. Stay a while.</p><audio ref={audio} src={`/api/tracks/${track.id}/audio`} preload="metadata" loop={loop} controlsList="nodownload" onContextMenu={e=>e.preventDefault()} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onWaiting={()=>setWaiting(true)} onPlaying={()=>setWaiting(false)} onCanPlay={()=>setWaiting(false)} onTimeUpdate={()=>setCurrent(audio.current?.currentTime||0)} onLoadedMetadata={()=>{if(audio.current&&Number.isFinite(audio.current.duration))setDuration(audio.current.duration);}} onProgress={()=>{const a=audio.current;if(a?.buffered.length)setBuffer(a.buffered.end(a.buffered.length-1));}} onError={()=>{if(!expired)setError('Unable to play this audio. Check your connection or try another browser.');setWaiting(false);}}/>
 <div className="seek-wrap"><input aria-label="Seek through audio" type="range" min="0" max={duration||1} step="0.1" value={current} disabled={expired} style={{background:`linear-gradient(to right, var(--accent) ${current/duration*100}%, #727272 ${current/duration*100}%, #727272 ${buffer/duration*100}%, #343434 ${buffer/duration*100}%)`}} onChange={e=>{if(audio.current){audio.current.currentTime=Number(e.target.value);setCurrent(Number(e.target.value));}}}/><div className="time-row"><span>{time(current)}</span><span>{time(duration)}</span></div></div>
 <div className="play-controls"><button className="icon-button" title="Replay from beginning" aria-label="Replay from beginning" disabled={expired} onClick={()=>{if(audio.current){audio.current.currentTime=0;void audio.current.play().catch(()=>setError('Unable to replay. Please try again.'));}}}><RotateCcw size={21}/></button><button className="play-button" aria-label={playing?'Pause':'Play'} disabled={expired} onClick={toggle}>{waiting?<span className="spinner"/>:playing?<Pause size={25} fill="currentColor"/>:<Play size={25} fill="currentColor"/>}</button><button className={`icon-button ${loop?'selected':''}`} title="Repeat track" aria-label="Repeat track" aria-pressed={loop} onClick={()=>setLoop(!loop)}><Repeat2 size={23}/></button></div>
 <div className="player-bottom"><span className="expiry"><Clock3 size={14}/>{remaining(track.expires,now)}</span><div className="volume"><button className="icon-button" aria-label={volume?'Mute':'Unmute'} onClick={()=>{const v=volume?0:1;setVolume(v);if(audio.current)audio.current.volume=v;}}>{volume?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><input aria-label="Volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{setVolume(+e.target.value);if(audio.current)audio.current.volume=+e.target.value;}}/></div></div>{error&&<p className="error" role="alert">{error}</p>}</div></div>;
}
